<?php
/**
 * ACF local field groups for editable page content.
 *
 * @package ViaR_Luxury
 */

function viar_register_acf_fields(): void {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group([
        'key' => 'group_viar_page_hero_content',
        'title' => 'ViaR Hero Content',
        'fields' => [
            [
                'key' => 'field_viar_hero_eyebrow',
                'label' => 'Hero Eyebrow',
                'name' => 'viar_hero_eyebrow',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_hero_title',
                'label' => 'Hero Title',
                'name' => 'viar_hero_title',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_hero_description',
                'label' => 'Hero Description',
                'name' => 'viar_hero_description',
                'type' => 'textarea',
                'rows' => 3,
            ],
            [
                'key' => 'field_viar_hero_image',
                'label' => 'Hero Image',
                'name' => 'viar_hero_image',
                'type' => 'image',
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
            ],
            [
                'key' => 'field_viar_card_image',
                'label' => 'Card / Secondary Image',
                'name' => 'viar_card_image',
                'type' => 'image',
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
                'instructions' => 'Optional secondary image used by page sections/cards where supported by template.',
            ],
            [
                'key' => 'field_viar_home_tours_label',
                'label' => 'Homepage Tours Label',
                'name' => 'viar_home_tours_label',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_home_tours_title',
                'label' => 'Homepage Tours Title',
                'name' => 'viar_home_tours_title',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_home_zigzag_row1_label',
                'label' => 'Homepage Zigzag Row 1 Label',
                'name' => 'viar_home_zigzag_row1_label',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_home_zigzag_row1_title',
                'label' => 'Homepage Zigzag Row 1 Title',
                'name' => 'viar_home_zigzag_row1_title',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_home_zigzag_row1_description',
                'label' => 'Homepage Zigzag Row 1 Description',
                'name' => 'viar_home_zigzag_row1_description',
                'type' => 'textarea',
                'rows' => 4,
            ],
            [
                'key' => 'field_viar_home_zigzag_row1_cta_label',
                'label' => 'Homepage Zigzag Row 1 CTA Label',
                'name' => 'viar_home_zigzag_row1_cta_label',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_home_zigzag_row1_cta_url',
                'label' => 'Homepage Zigzag Row 1 CTA URL',
                'name' => 'viar_home_zigzag_row1_cta_url',
                'type' => 'url',
            ],
            [
                'key' => 'field_viar_home_zigzag_row1_image',
                'label' => 'Homepage Zigzag Row 1 Image',
                'name' => 'viar_home_zigzag_row1_image',
                'type' => 'image',
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
            ],
            [
                'key' => 'field_viar_home_zigzag_row2_label',
                'label' => 'Homepage Zigzag Row 2 Label',
                'name' => 'viar_home_zigzag_row2_label',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_home_zigzag_row2_title',
                'label' => 'Homepage Zigzag Row 2 Title',
                'name' => 'viar_home_zigzag_row2_title',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_home_zigzag_row2_description',
                'label' => 'Homepage Zigzag Row 2 Description',
                'name' => 'viar_home_zigzag_row2_description',
                'type' => 'textarea',
                'rows' => 4,
            ],
            [
                'key' => 'field_viar_home_zigzag_row2_cta_label',
                'label' => 'Homepage Zigzag Row 2 CTA Label',
                'name' => 'viar_home_zigzag_row2_cta_label',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_home_zigzag_row2_cta_url',
                'label' => 'Homepage Zigzag Row 2 CTA URL',
                'name' => 'viar_home_zigzag_row2_cta_url',
                'type' => 'url',
            ],
            [
                'key' => 'field_viar_home_zigzag_row2_image',
                'label' => 'Homepage Zigzag Row 2 Image',
                'name' => 'viar_home_zigzag_row2_image',
                'type' => 'image',
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
            ],
            [
                'key' => 'field_viar_home_standard_label',
                'label' => 'Homepage Standards Label',
                'name' => 'viar_home_standard_label',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_home_standard_title',
                'label' => 'Homepage Standards Title',
                'name' => 'viar_home_standard_title',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_home_standard_item1_title',
                'label' => 'Homepage Standards Item 1 Title',
                'name' => 'viar_home_standard_item1_title',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_home_standard_item1_desc',
                'label' => 'Homepage Standards Item 1 Description',
                'name' => 'viar_home_standard_item1_desc',
                'type' => 'textarea',
                'rows' => 3,
            ],
            [
                'key' => 'field_viar_home_standard_item2_title',
                'label' => 'Homepage Standards Item 2 Title',
                'name' => 'viar_home_standard_item2_title',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_home_standard_item2_desc',
                'label' => 'Homepage Standards Item 2 Description',
                'name' => 'viar_home_standard_item2_desc',
                'type' => 'textarea',
                'rows' => 3,
            ],
            [
                'key' => 'field_viar_home_standard_item3_title',
                'label' => 'Homepage Standards Item 3 Title',
                'name' => 'viar_home_standard_item3_title',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_home_standard_item3_desc',
                'label' => 'Homepage Standards Item 3 Description',
                'name' => 'viar_home_standard_item3_desc',
                'type' => 'textarea',
                'rows' => 3,
            ],
            [
                'key' => 'field_viar_home_testimonials_label',
                'label' => 'Homepage Testimonials Label',
                'name' => 'viar_home_testimonials_label',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_home_testimonials_title',
                'label' => 'Homepage Testimonials Title',
                'name' => 'viar_home_testimonials_title',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_home_testimonial_1_quote',
                'label' => 'Homepage Testimonial 1 Quote',
                'name' => 'viar_home_testimonial_1_quote',
                'type' => 'textarea',
                'rows' => 3,
            ],
            [
                'key' => 'field_viar_home_testimonial_1_author',
                'label' => 'Homepage Testimonial 1 Author',
                'name' => 'viar_home_testimonial_1_author',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_home_testimonial_2_quote',
                'label' => 'Homepage Testimonial 2 Quote',
                'name' => 'viar_home_testimonial_2_quote',
                'type' => 'textarea',
                'rows' => 3,
            ],
            [
                'key' => 'field_viar_home_testimonial_2_author',
                'label' => 'Homepage Testimonial 2 Author',
                'name' => 'viar_home_testimonial_2_author',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_hero_cta_label',
                'label' => 'Hero CTA Label',
                'name' => 'viar_hero_cta_label',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_hero_cta_url',
                'label' => 'Hero CTA URL',
                'name' => 'viar_hero_cta_url',
                'type' => 'url',
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                ],
            ],
        ],
        'style' => 'default',
        'position' => 'normal',
        'show_in_rest' => 1,
        'description' => 'Edit designed page sections here. Hero Image controls the main hero visual; Card / Secondary Image is used where the template supports it. Keep the page editor empty to use the theme layout.',
    ]);
        'title' => 'ViaR Fleet Booking Content',
        'fields' => [
            [
                'key' => 'field_viar_fleet_subtitle',
                'label' => 'Fleet Subtitle',
                'name' => 'viar_fleet_subtitle',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_fleet_title',
                'label' => 'Fleet Title',
                'name' => 'viar_fleet_title',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_fleet_description',
                'label' => 'Fleet Description',
                'name' => 'viar_fleet_description',
                'type' => 'textarea',
                'rows' => 4,
            ],
            [
                'key' => 'field_viar_fleet_image',
                'label' => 'Fleet Image URL',
                'name' => 'viar_fleet_image',
                'type' => 'url',
            ],
            [
                'key' => 'field_viar_fleet_booking_shortcode',
                'label' => 'BookingPress Shortcode',
                'name' => 'viar_fleet_booking_shortcode',
                'type' => 'text',
                'instructions' => 'Example: [bookingpress_form service_id=\"1\"]',
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'templates/page-fleet-booking.php',
                ],
            ],
        ],
        'style' => 'default',
        'position' => 'normal',
        'show_in_rest' => 1,
        'description' => 'Fleet booking page content and BookingPress shortcode for this template.',
    ]);

    acf_add_local_field_group([
        'key' => 'group_viar_fleet_post_fields',
        'title' => 'ViaR Fleet Post Fields',
        'fields' => [
            [
                'key' => 'field_viar_fleet_card_label',
                'label' => 'Fleet Card Label',
                'name' => 'viar_fleet_card_label',
                'type' => 'text',
                'instructions' => 'Small text shown on VIP Transfers listing card.',
            ],
            [
                'key' => 'field_viar_fleet_card_image',
                'label' => 'Fleet Card Image',
                'name' => 'viar_fleet_card_image',
                'type' => 'image',
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
            ],
            [
                'key' => 'field_viar_fleet_hero_image',
                'label' => 'Fleet Hero Image (Single Page)',
                'name' => 'viar_fleet_hero_image',
                'type' => 'image',
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
            ],
            [
                'key' => 'field_viar_fleet_booking_shortcode_post',
                'label' => 'BookingPress Shortcode',
                'name' => 'viar_fleet_booking_shortcode',
                'type' => 'text',
                'instructions' => 'Example: [bookingpress_form service_id="1"]',
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'viar_fleet',
                ],
            ],
        ],
        'style' => 'default',
        'position' => 'normal',
        'show_in_rest' => 1,
        'description' => 'Fleet Card Image is used on VIP Transfers listing cards. Fleet Hero Image is used on the single fleet page. BookingPress Shortcode controls the booking form.',
    ]);

    acf_add_local_field_group([
        'key' => 'group_viar_tour_post_fields',
        'title' => 'ViaR Bespoke Tour Fields',
        'fields' => [
            [
                'key' => 'field_viar_tour_tab_listing',
                'label' => 'Listing',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ],
            [
                'key' => 'field_viar_tour_card_image',
                'label' => 'Tour Card Image',
                'name' => 'viar_tour_card_image',
                'type' => 'image',
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
                'instructions' => 'Used on Bespoke Tours listing and homepage cards.',
            ],
            [
                'key' => 'field_viar_tour_tab_hero',
                'label' => 'Hero & Introduction',
                'name' => '',
                'type' => 'tab',
            ],
            [
                'key' => 'field_viar_tour_hero_image',
                'label' => 'Hero Image',
                'name' => 'viar_tour_hero_image',
                'type' => 'image',
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
            ],
            [
                'key' => 'field_viar_tour_collection_label',
                'label' => 'Collection Label',
                'name' => 'viar_tour_collection_label',
                'type' => 'text',
                'instructions' => 'Eyebrow above the tour title, e.g. Signature Collection.',
                'default_value' => 'Signature Collection',
            ],
            [
                'key' => 'field_viar_tour_intro_title',
                'label' => 'Introduction Title',
                'name' => 'viar_tour_intro_title',
                'type' => 'text',
                'instructions' => 'Editorial headline below the hero.',
            ],
            [
                'key' => 'field_viar_tour_intro_lead',
                'label' => 'Introduction Lead',
                'name' => 'viar_tour_intro_lead',
                'type' => 'textarea',
                'rows' => 4,
                'instructions' => 'Italic lead paragraph. Falls back to excerpt if empty.',
            ],
            [
                'key' => 'field_viar_tour_intro_body',
                'label' => 'Introduction Body',
                'name' => 'viar_tour_intro_body',
                'type' => 'textarea',
                'rows' => 5,
                'instructions' => 'Supporting paragraph. Falls back to post content if empty.',
            ],
            [
                'key' => 'field_viar_tour_tab_glance',
                'label' => 'At a Glance',
                'name' => '',
                'type' => 'tab',
            ],
            [
                'key' => 'field_viar_tour_duration',
                'label' => 'Duration',
                'name' => 'viar_tour_duration',
                'type' => 'text',
                'placeholder' => '8 Days / 7 Nights',
            ],
            [
                'key' => 'field_viar_tour_location',
                'label' => 'Location',
                'name' => 'viar_tour_location',
                'type' => 'text',
                'placeholder' => 'Southern Peloponnese',
            ],
            [
                'key' => 'field_viar_tour_pace',
                'label' => 'Pace',
                'name' => 'viar_tour_pace',
                'type' => 'text',
                'placeholder' => 'Contemplative',
            ],
            [
                'key' => 'field_viar_tour_best_season',
                'label' => 'Best Season',
                'name' => 'viar_tour_best_season',
                'type' => 'text',
                'placeholder' => 'May – October',
            ],
            [
                'key' => 'field_viar_tour_tab_experiences',
                'label' => 'Curated Experiences',
                'name' => '',
                'type' => 'tab',
            ],
            [
                'key' => 'field_viar_tour_experiences_label',
                'label' => 'Section Eyebrow',
                'name' => 'viar_tour_experiences_label',
                'type' => 'text',
                'default_value' => 'The Narrative',
            ],
            [
                'key' => 'field_viar_tour_experiences_title',
                'label' => 'Section Title',
                'name' => 'viar_tour_experiences_title',
                'type' => 'text',
                'default_value' => 'Curated Experiences',
            ],
            [
                'key' => 'field_viar_tour_experience_1_title',
                'label' => 'Experience 1 — Title',
                'name' => 'viar_tour_experience_1_title',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_tour_experience_1_description',
                'label' => 'Experience 1 — Description',
                'name' => 'viar_tour_experience_1_description',
                'type' => 'textarea',
                'rows' => 3,
            ],
            [
                'key' => 'field_viar_tour_experience_1_image',
                'label' => 'Experience 1 — Image',
                'name' => 'viar_tour_experience_1_image',
                'type' => 'image',
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
            ],
            [
                'key' => 'field_viar_tour_experience_2_title',
                'label' => 'Experience 2 — Title',
                'name' => 'viar_tour_experience_2_title',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_tour_experience_2_description',
                'label' => 'Experience 2 — Description',
                'name' => 'viar_tour_experience_2_description',
                'type' => 'textarea',
                'rows' => 3,
            ],
            [
                'key' => 'field_viar_tour_experience_2_image',
                'label' => 'Experience 2 — Image',
                'name' => 'viar_tour_experience_2_image',
                'type' => 'image',
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
            ],
            [
                'key' => 'field_viar_tour_experience_3_title',
                'label' => 'Experience 3 — Title',
                'name' => 'viar_tour_experience_3_title',
                'type' => 'text',
            ],
            [
                'key' => 'field_viar_tour_experience_3_description',
                'label' => 'Experience 3 — Description',
                'name' => 'viar_tour_experience_3_description',
                'type' => 'textarea',
                'rows' => 3,
            ],
            [
                'key' => 'field_viar_tour_experience_3_image',
                'label' => 'Experience 3 — Image',
                'name' => 'viar_tour_experience_3_image',
                'type' => 'image',
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
            ],
            [
                'key' => 'field_viar_tour_quote',
                'label' => 'Pull Quote',
                'name' => 'viar_tour_quote',
                'type' => 'textarea',
                'rows' => 3,
            ],
            [
                'key' => 'field_viar_tour_quote_attribution',
                'label' => 'Quote Attribution',
                'name' => 'viar_tour_quote_attribution',
                'type' => 'text',
                'placeholder' => '— Julian Arnault, Expedition Lead',
            ],
            [
                'key' => 'field_viar_tour_tab_cta',
                'label' => 'Inquiry CTA',
                'name' => '',
                'type' => 'tab',
            ],
            [
                'key' => 'field_viar_tour_cta_title',
                'label' => 'CTA Title',
                'name' => 'viar_tour_cta_title',
                'type' => 'text',
                'default_value' => 'Begin Your Inquiry',
            ],
            [
                'key' => 'field_viar_tour_cta_description',
                'label' => 'CTA Description',
                'name' => 'viar_tour_cta_description',
                'type' => 'textarea',
                'rows' => 3,
            ],
            [
                'key' => 'field_viar_tour_cta_label',
                'label' => 'CTA Button Label',
                'name' => 'viar_tour_cta_label',
                'type' => 'text',
                'default_value' => 'Inquire About This Journey',
            ],
            [
                'key' => 'field_viar_tour_cta_url',
                'label' => 'CTA Button URL',
                'name' => 'viar_tour_cta_url',
                'type' => 'url',
                'instructions' => 'Defaults to the site Inquiry page.',
            ],
            [
                'key' => 'field_viar_tour_brochure',
                'label' => 'Brochure File',
                'name' => 'viar_tour_brochure',
                'type' => 'file',
                'return_format' => 'url',
                'library' => 'all',
                'instructions' => 'Optional PDF for the mobile “Download Brochure” button.',
            ],
            [
                'key' => 'field_viar_tour_cta_bg_image',
                'label' => 'CTA Background Texture',
                'name' => 'viar_tour_cta_bg_image',
                'type' => 'image',
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
                'instructions' => 'Optional subtle background for the desktop CTA panel.',
            ],
            [
                'key' => 'field_viar_tour_tab_booking',
                'label' => 'Booking',
                'name' => '',
                'type' => 'tab',
            ],
            [
                'key' => 'field_viar_tour_booking_shortcode',
                'label' => 'BookingPress Shortcode',
                'name' => 'viar_tour_booking_shortcode',
                'type' => 'text',
                'instructions' => 'Optional. Example: [bookingpress_form service_id="2"]',
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'viar_bespoke_tour',
                ],
            ],
        ],
        'style' => 'default',
        'position' => 'normal',
        'show_in_rest' => 1,
        'description' => 'Tour Card Image is used on listings and the homepage carousel. Fill Hero & Introduction, At a Glance, Experiences 1–3, quote, and Inquiry CTA for the tour detail page.',
    ]);
}
add_action('acf/init', 'viar_register_acf_fields');
